### ISSUE TITLE
NoSuchMethodError in CartesianChartModelProducer after upgrading from 3.1.0 to 3.2.x

### ISSUE THREAD

**Issue by mubashirpa** [patrykandpatrick/vico#1500]
### Example

After upgrading Vico from 3.1.0 to 3.2.0 or 3.2.1, opening a screen containing a CartesianChartHost causes an immediate crash.

The same code works correctly on 3.1.0.

The crash occurs as soon as the chart composable is displayed.

```kotlin
private val BottomAxisLabelKey = ExtraStore.Key<List<String>>()

@Composable
fun HeartRateChart(
    data: Map<String, Int>,
    modifier: Modifier = Modifier,
) {
    val modelProducer = remember { CartesianChartModelProducer() }

    LaunchedEffect(data) {
        if (data.isNotEmpty()) {
            modelProducer.runTransaction {
                lineSeries { series(data.values) }
                extras { it[BottomAxisLabelKey] = data.keys.toList() }
            }
        }
    }

    CartesianChartHost(
        chart =
            rememberCartesianChart(
                rememberLineCartesianLayer(),
                startAxis = VerticalAxis.rememberStart(),
                bottomAxis = HorizontalAxis.rememberBottom(),
            ),
        modelProducer = modelProducer,
        modifier = modifier,
        scrollState = rememberVicoScrollState(scrollEnabled = false),
    )
}
```

### How to reproduce

1. Use Vico 3.1.0 and verify the chart screen works.
2. Upgrade to 3.2.0 or 3.2.1.
3. Open a screen containing CartesianChartHost.
4. Observe the application crash.

### Observed behavior

Application crashes immediately when the chart screen is opened with the following exception:

```
Fatal Exception: java.lang.NoSuchMethodError: No static method tryLock$default(Lkotlinx/coroutines/sync/Mutex;Ljava/lang/Object;ILjava/lang/Object;)Z in class Lkotlinx/coroutines/sync/Mutex; or its super classes (declaration of 'kotlinx.coroutines.sync.Mutex' appears in /data/app/~~hI4WBaFnpWVKPzIhpR7AWw==/com.zenithratech.zengadgets.dev-pQK1BvUdXs-mE4f3HNg2hg==/base.apk!classes32.dex)
       at com.patrykandpatrick.vico.compose.cartesian.data.CartesianChartModelProducer.getCachedData$compose(CartesianChartModelProducer.kt:124)
       at com.patrykandpatrick.vico.compose.cartesian.data.CartesianChartModelKt.collectAsState(CartesianChartModel.kt:135)
       at com.patrykandpatrick.vico.compose.cartesian.CartesianChartHostKt.CartesianChartHost(CartesianChartHost.kt:94)
       at com.zenithratech.zenring.ui.activity.components.DistanceChartKt.DistanceChart(DistanceChart.kt:89)
       at com.zenithratech.zenring.ui.activity.components.DistanceChartKt.DistanceChart(DistanceChart.kt:71)
       at com.zenithratech.zenring.ui.activity.ActivityDetailScreenKt.ActivityDetailScreen$lambda$10$0$1$2(ActivityDetailScreen.kt:162)
       at com.zenithratech.zenring.ui.activity.ActivityDetailScreenKt.$r8$lambda$5hQekIxsBZS39B8VyLXTDpZXnO8()
       at com.zenithratech.zenring.ui.activity.ActivityDetailScreenKt$$ExternalSyntheticLambda8.invoke(D8$$SyntheticClass)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at com.zenithratech.zenring.ui.activity.ActivityDetailScreenKt.ActivityCard$lambda$0(ActivityDetailScreen.kt:380)
       at com.zenithratech.zenring.ui.activity.ActivityDetailScreenKt$$ExternalSyntheticLambda27.invoke(D8$$SyntheticClass)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:131)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at androidx.compose.material3.CardKt$Card$1.invoke(Card.kt:856)
       at androidx.compose.material3.CardKt$Card$1.invoke(Card.kt:95)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:130)
       at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:110)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:408)
       at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:107)
       at androidx.compose.material3.CardKt.Card(Card.kt:88)
       at androidx.compose.material3.CardKt.OutlinedCard(Card.kt:299)
       at com.zenithratech.zenring.ui.activity.ActivityDetailScreenKt.ActivityCard(ActivityDetailScreen.kt:325)
       at com.zenithratech.zenring.ui.activity.ActivityDetailScreenKt.ActivityDetailScreen$lambda$10(ActivityDetailScreen.kt:148)
       at com.zenithratech.zenring.ui.activity.ActivityDetailScreenKt$$ExternalSyntheticLambda30.invoke(D8$$SyntheticClass)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:428)
       at com.patrykandpatrick.vico.compose.common.VicoThemeKt.ProvideVicoTheme(VicoTheme.kt:102)
       at com.zenithratech.zenring.ui.components.AppVicoThemeKt.AppVicoTheme(AppVicoTheme.kt:10)
       at com.zenithratech.zenring.ui.activity.ActivityDetailScreenKt.ActivityDetailScreen(ActivityDetailScreen.kt:125)
       at com.zenithratech.zenring.ui.navigation.ZenRingNavGraphKt.destinations$lambda$19(ZenRingNavGraph.kt:811)
       at com.zenithratech.zenring.ui.navigation.ZenRingNavGraphKt$$ExternalSyntheticLambda100.invoke(D8$$SyntheticClass)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:143)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke(NavHost.kt:712)
       at androidx.navigation.compose.NavHostKt$NavHost$32$1.invoke(NavHost.kt:711)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:408)
       at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:82)
       at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:69)
       at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
       at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:56)
       at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:55)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:408)
       at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:51)
       at androidx.navigation.compose.NavHostKt$NavHost$32.invoke(NavHost.kt:711)
       at androidx.navigation.compose.NavHostKt$NavHost$32.invoke(NavHost.kt:691)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:143)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:863)
       at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:853)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:131)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:762)
       at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:835)
       at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:818)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
       at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:873)
       at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:663)
       at androidx.navigation.compose.NavHostKt.NavHost$lambda$80(:25)
       at androidx.navigation.compose.NavHostKt$$ExternalSyntheticLambda3.invoke(D8$$SyntheticClass)
       at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:204)
       at androidx.compose.runtime.GapComposer.recomposeToGroupEnd(GapComposer.kt:1678)
       at androidx.compose.runtime.GapComposer.skipCurrentGroup(GapComposer.kt:2014)
       at androidx.compose.runtime.GapComposer.doCompose-aFTiNEg(GapComposer.kt:2655)
       at androidx.compose.runtime.GapComposer.recompose-aFTiNEg$runtime(GapComposer.kt:2577)
       at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:1164)
       at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1318)
       at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:191)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend$lambda$2(Recomposer.kt:655)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass)
       at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:39)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:108)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:2528)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:2539)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1817)
       at android.view.Choreographer.doFrame(Choreographer.java:1571)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:2364)
       at android.os.Handler.handleCallback(Handler.java:1051)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loopOnce(Looper.java:266)
       at android.os.Looper.loop(Looper.java:361)
       at android.app.ActivityThread.main(ActivityThread.java:10382)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:675)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1002)
```

### Expected behavior

The chart should render normally without crashing, as it does with Vico 3.1.0.

### Module(s)

compose-m3

### Platform(s)

Android

### Platform version(s)

Android 16 (Origin OS 6)

### Vico version(s)

3.2.0-next.5

### Additional information

Vico version:

- Works: 3.1.0
- Crashes: 3.2.0, 3.2.1

Compose chart implementation uses:

- CartesianChartHost
- CartesianChartModelProducer
- rememberLineCartesianLayer
- runTransaction

The crash originates from CartesianChartModelProducer.getCachedData() during composition.
The exception appears to be related to a missing coroutine Mutex.tryLock$default method, which may indicate a dependency compatibility issue introduced in Vico 3.2.x.

**Comment by mubashirpa** [comment]
Also there was no option for the version 3.2.x in Vico version(s)

**Comment by mubashirpa** [comment]
Everytime when I try to report a bug it will be closed automatically, now i know why there are no active issues 😂. I have also tried adding coroutines dependency with version 1.11.0, and still it crashed.

**Comment by mubashirpa** [comment]
I wasn't getting any crash with previous version, but with latest version. so for now i have rollback to 3.1.0

**Comment by patrickmichalik** [comment]
Hello, @mubashirpa!

Thanks for calling out the out-of-date version drop-down; we’ve fixed that. By no means are bug reports closed unconditionally. Valid, reproducible ones are accepted and promptly addressed, as the issue history shows.

On the crash: As pointed out above, the stack trace points to binary incompatibility rather than a Vico bug. The `kotlinx-coroutines-core` version actually resolved and packaged by your app doesn’t match what Vico `3.2.x` was compiled against. Explicitly adding version `1.11.0` may be insufficient if something else still pins an older one. Could you run `./gradlew :app:dependencyInsight --dependency kotlinx-coroutines-core` and share the output?

**Comment by mubashirpa** [comment]
@patrickmichalik Okay i will check. The reason i said the reports are closing because last when i tried to report a bug from vico (A horizontal decoration line is drawn outside the vico chart) it was closed automatically saying something regarding the example i give contains some imports from outside the file or something, anyway thanks. You guyz are doing a great work with this library.

**Comment by patrickmichalik** [comment]
Thanks for the kind words!

About the previous closure: We ask for examples to be self-contained so that we can copy them into a clean project and verify the problem without guesswork. We do monitor all issues, though, so if you’re unsure what part of a report needs adjusting, feel free to request clarification.

We’ll wait for the `dependencyInsight` output from you and take another look from there.
