### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt

### ISSUE THREAD

**Issue by subhashisbhowmik** [patrykandpatrick/vico#407]
**Describe the bug**
Facing a NoClassDefFoundError with Vico version >1.9.2 (Tried 1.13.0-alpha.2, 1.12.0, 1.11.0, 1.10.0). Works fine with 1.9.2
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
at com.patrykandpatrick.vico.compose.chart.ChartsKt.ChartImpl(Charts.kt:327)
at com.patrykandpatrick.vico.compose.chart.ChartsKt$Chart$1.invoke(Charts.kt:138)
at com.patrykandpatrick.vico.compose.chart.ChartsKt$Chart$1.invoke(Charts.kt:136)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:129)
at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:128)
at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2522)
at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2814)
at com.patrykandpatrick.vico.compose.chart.ChartsKt.ChartBox(Charts.kt:458)
at com.patrykandpatrick.vico.compose.chart.ChartsKt.Chart(Charts.kt:136)
```

build.gradle.kts (:app)
```
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("androidx.navigation.safeargs")
    id("dagger.hilt.android.plugin")
    id("com.google.devtools.ksp")
}

android {
    namespace = "..."
    compileSdk = 34

    defaultConfig {
        applicationId = "..."
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
        viewBinding = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.3"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

//// Uncomment to add Compiler Flags
//tasks.withType<JavaCompile> {
//    options.compilerArgs.addAll(listOf("-Xlint:unchecked", "-Xlint:deprecation"))
//}

dependencies {
    implementation("com.google.android.material:material:1.9.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")

    // Autofill
    implementation("androidx.autofill:autofill:1.3.0-alpha01")

    // OTP
    implementation("com.google.android.gms:play-services-auth:20.7.0")
    implementation("com.google.android.gms:play-services-auth-api-phone:18.0.1")

    val navVersion = "2.7.1"

    // Kotlin nav
    implementation("androidx.navigation:navigation-fragment-ktx:$navVersion")
    implementation("androidx.navigation:navigation-ui-ktx:$navVersion")
    // Feature module Support
    implementation("androidx.navigation:navigation-dynamic-features-fragment:$navVersion")

    // Testing Navigation
    androidTestImplementation("androidx.navigation:navigation-testing:$navVersion")

    // Jetpack Compose Integration
    implementation("androidx.navigation:navigation-compose:$navVersion")

    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.6.2")
    implementation("androidx.activity:activity-compose:1.7.2")
    implementation(platform("androidx.compose:compose-bom:2023.03.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("com.github.felHR85:UsbSerial:6.1.0")

    // Retrofit
    implementation("com.squareup.retrofit2:retrofit:2.5.0")
    implementation("com.squareup.retrofit2:converter-gson:2.5.0")

    // Dagger Hilt
    implementation("com.google.dagger:hilt-android:2.48")
    implementation("androidx.hilt:hilt-navigation-compose:1.1.0-alpha01")
    ksp("com.google.dagger:hilt-compiler:2.48")

    // Vico chart dependencies
    val vicoVersion = "1.12.0"
    // Includes the core logic for charts and other elements.
    implementation("com.patrykandpatrick.vico:core:$vicoVersion")
    // For Jetpack Compose.
    implementation("com.patrykandpatrick.vico:compose:$vicoVersion")
    // For the view system.
    implementation("com.patrykandpatrick.vico:views:$vicoVersion")
    // For `compose`. Creates a `ChartStyle` based on an M2 Material Theme.
//    implementation("com.patrykandpatrick.vico:compose-m2:$vicoVersion")
    // For `compose`. Creates a `ChartStyle` based on an M3 Material Theme.
    implementation("com.patrykandpatrick.vico:compose-m3:$vicoVersion")

    // Material Icons
    runtimeOnly("androidx.compose.material:material-icons-core:1.6.0-alpha05")

    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    androidTestImplementation(platform("androidx.compose:compose-bom:2023.03.00"))
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
}
```
build.gradle.kts (Project)
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id("com.android.application") version "8.1.1" apply false //8.1.0
    id("org.jetbrains.kotlin.android") version "1.9.10" apply false
    id("com.google.devtools.ksp") version "1.9.10-1.0.13" apply false
}

buildscript {
    repositories {
        google()
    }
    dependencies {
        val navVersion = "2.7.2" //2.5.0
        classpath("androidx.navigation:navigation-safe-args-gradle-plugin:$navVersion")
        classpath("com.google.dagger:hilt-android-gradle-plugin:2.48")
    }
}
```

Usage:
```
Chart(
            chart = lineChart(),
            chartModelProducer = producer,
            startAxis = rememberStartAxis(),
            bottomAxis = rememberBottomAxis(),
            diffAnimationSpec = snap()
        ) {
            3F
        }
```

Tried dead ends: Clean build, invalidate caches/restart

**Module**

- [x] `compose`
- [x] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [x] `core` (select if none of the above apply)

**To reproduce**
Please try to reproduce it  with the same gradle scripts

**Expected behavior**
No runtime error

**Screenshots**
N/A

**Android versions**
13

**Additional context**
N/A

**Comment by patrickmichalik** [comment]
Hello! Please see #366. Version 2023.03.00 of the Jetpack Compose BOM and version 1.12.0 of Vico are incompatible. For Vico 1.12.0, please use version 2023.09.00 of the BOM. As for Vico 1.13.0 Alpha 2, it uses version 2023.09.01 of the BOM.

**Comment by subhashisbhowmik** [comment]
Hi @patrickmichalik , appreciate the quick response!

I have updated the build file accordingly but I'm still seeing the same issue (Also tried clean build and invalidate caches)
```
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("androidx.navigation.safeargs")
    id("dagger.hilt.android.plugin")
    id("com.google.devtools.ksp")
}

android {
    namespace = "com.artemis.sync"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.artemis.sync"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        debug {
            isDebuggable = true
        }
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
        viewBinding = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.3"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

//// Uncomment to add Compiler Flags
//tasks.withType<JavaCompile> {
//    options.compilerArgs.addAll(listOf("-Xlint:unchecked", "-Xlint:deprecation"))
//}

dependencies {
    implementation("com.google.android.material:material:1.9.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")

    // Autofill
    implementation("androidx.autofill:autofill:1.3.0-alpha01")

    // OTP
    implementation("com.google.android.gms:play-services-auth:20.7.0")
    implementation("com.google.android.gms:play-services-auth-api-phone:18.0.1")

    val navVersion = "2.7.1"

    // Kotlin nav
    implementation("androidx.navigation:navigation-fragment-ktx:$navVersion")
    implementation("androidx.navigation:navigation-ui-ktx:$navVersion")
    // Feature module Support
    implementation("androidx.navigation:navigation-dynamic-features-fragment:$navVersion")

    // Testing Navigation
    androidTestImplementation("androidx.navigation:navigation-testing:$navVersion")

    // Jetpack Compose Integration
    implementation("androidx.navigation:navigation-compose:$navVersion")

    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.6.2")
    implementation("androidx.activity:activity-compose:1.7.2")
    implementation(platform("androidx.compose:compose-bom:2023.09.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    debugImplementation("androidx.compose.ui:ui-tooling")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")

    implementation("com.github.felHR85:UsbSerial:6.1.0")

    // Retrofit
    implementation("com.squareup.retrofit2:retrofit:2.5.0")
    implementation("com.squareup.retrofit2:converter-gson:2.5.0")

    // Dagger Hilt
    implementation("com.google.dagger:hilt-android:2.48")
    implementation("androidx.hilt:hilt-navigation-compose:1.1.0-alpha01")
    ksp("com.google.dagger:hilt-compiler:2.48")

    // Vico chart dependencies
    val vicoVersion = "1.12.0"
    // Includes the core logic for charts and other elements.
    implementation("com.patrykandpatrick.vico:core:$vicoVersion")
    // For Jetpack Compose.
    implementation("com.patrykandpatrick.vico:compose:$vicoVersion")
    // For the view system.
    implementation("com.patrykandpatrick.vico:views:$vicoVersion")
    // For `compose`. Creates a `ChartStyle` based on an M2 Material Theme.
//    implementation("com.patrykandpatrick.vico:compose-m2:$vicoVersion")
    // For `compose`. Creates a `ChartStyle` based on an M3 Material Theme.
    implementation("com.patrykandpatrick.vico:compose-m3:$vicoVersion")

    // Material Icons
    runtimeOnly("androidx.compose.material:material-icons-core:1.6.0-alpha05")

    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    androidTestImplementation(platform("androidx.compose:compose-bom:2023.09.00"))
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
}
```

Am I missing something?

**Comment by patrickmichalik** [comment]
Please try updating `androidx.compose.material:material-icons-core`:

```diff
- runtimeOnly("androidx.compose.material:material-icons-core:1.6.0-alpha05")
+ runtimeOnly("androidx.compose.material:material-icons-core:1.6.0-alpha06")
```

**Comment by subhashisbhowmik** [comment]
Yes that solved it! Never thought that material icons version would be the problem. Thanks!
 
Although I'm still seeing the runtime issue mentioned on #408 for 1.12.0, and a different runtime issue in 1.13.0-alpha.2, I'll try to debug that (must be due to the major changes in vico). Closing this.

**Comment by patrickmichalik** [comment]
You’re welcome! I’m glad that this issue is resolved. I’ll get back to you under #408 shortly.
